# Trigger!
language: java
script: ant package
deploy:
   edge: true
   provider: cloudfoundry
   username: deenathayalan.pandiraj@verizon.com
   password: Verizon1
   api: https://api.run.pivotal.io
   organization: AcssCognizon
   space: development
